### ISSUE TITLE
Make secp module a part of crypto

### ISSUE THREAD

**Issue by jacobheun** [libp2p/js-libp2p-crypto#135]
Pulling [this convo](https://github.com/libp2p/js-peer-id/pull/85#issuecomment-448384609) here to discuss.

> @jacobheun there's a ticket in https://github.com/libp2p/js-libp2p-crypto-secp256k1 to support secp keys in the latest libp2p. You can't unmarshal private keys since the underlying signature changed in peerId (https://github.com/libp2p/js-libp2p-crypto-secp256k1/pulls). Is there any reason to keep secp256 in it's own package at this point? Isn't it directly included in libp2p crypto now? Apologies if this is the wrong place to discuss.

Should we just pull https://github.com/libp2p/js-libp2p-crypto-secp256k1 into libp2p-crypto?

One of the things I've encountered working on adding support for specifying key types, https://github.com/libp2p/js-peer-id/pull/85, is that the interface between keys is not consistent; such as https://github.com/libp2p/js-libp2p-crypto/issues/129.

I think whether or not we should pull secp256k1 into libp2p crypto could be argued either way. (Have crypto be modular or keep it all in one place.) Regardless of which direction we go, we need to improve the public interface testing to ensure we fully support each key.

**Comment by mkg20001** [comment]
My 2cents:
Moving https://github.com/libp2p/js-libp2p-crypto-secp256k1 here does sound like a good idea since tests are somewhat chicken-egg (js-libp2p-crypto uses a stub secp256k1 implementation, js-libp2p-crypto-secp256k1 depends on js-libp2p-crypto for testing anyways) and secp256k1 is used in a lot of places where js-libp2p-crypto is used since SECIO depends on it.

But the APIs for modular cryptos should still be kept because there are a lot of keytypes that won't get a lot of usage

Additionally the way additional cryptos get loaded should be improved. Currently it only autoloads secp256k1 if it exists, instead it should just automatically load any `libp2p-crypto-*` extensions.

**Comment by dignifiedquire** [comment]
There was a lot of discussion around this in the past, and one of the issues with the secp module is that it has native dependencies and increases the total build size of this package when you might not actually want this, e.g. in js-ipfs builds.

**Comment by jacobheun** [comment]
This is done, closing.
