### ISSUE TITLE
Cross-Browser compatibility

### ISSUE THREAD

**Issue by dignifiedquire** [libp2p/js-libp2p-crypto#18]
Due to the changes in #12 (the move to mainly webcrypto) browser support drops to only Firefox and Chrome. Even though Safari, IE11 and Edge implement `crypto.subtle` they don't support all algorithms that we require. Namely
- `AES-CTR`: Safari, Mobile Safari, Edge, IE11
- `ECDH`: Safari, Mobile Safari, ~~Mobile Chrome~~, Edge
- `RSASSA-PKCS1-v1_5`: Safari, Mobile Safari, IE11
-  `HMAC`: Mobile Safari

Given that currently only Firefox and Chrome support webrtc the impact of this might not be that large, but we should investigate in polyfills which can be included by projects that want to support other browsers. 
We don't want to ship polyfills by default though, as that would increase the size of this and all dependent modules drastically. 

Please give feedback if this is okay for now, or if this is an issue for you and of course solutions and suggestions.

**Comment by diasdavid** [comment]
Oh, didn't realise from the convo in IRC that Mobile Chrome was also in jeopardy with the async crypto PR.

The performance we get from moving to async crypto is quite significant plus the bundle size reduce. It would be interesting to know how easy it is to shim the missing algorithms in a way that they can be added to the global scope of the Browser, so that js-ipfs implementation wise doesn't have to change.

Found https://www.npmjs.com/package/webcrypto-shim but seems that is far from being complete.

**Comment by dignifiedquire** [comment]
Turns out, mobile chrome is fine, the version on Sauce Labs is just super old.

**Comment by diasdavid** [comment]
What about Internet Explorer and Mobile Firefox?

**Comment by dignifiedquire** [comment]
- Mobile Firefox, no idea can't test it
- added IE11

**Comment by achingbrain** [comment]
Closing because everything is Chrome now.
